# Cloudflare Pages configuration
[build]
command = "npm run build"

# For Pages deployment
pages_build_output_dir = "out"

[build.environment]
NODE_VERSION = "18"

# Explicitly exclude large cache files
[[build.exclude]]
files = [".next/cache/**"]

[[build.exclude]]
files = ["cache/**"]

