[build]
command = "npm run build"
publish = "out"

[build.environment]
NODE_VERSION = "18"

[site]
bucket = "out"

# Explicitly exclude large cache files
[[build.excludedFiles]]
path = ".next/cache/**"

[[build.excludedFiles]]
path = "cache/**"
